export const NODE_TYPE_EMAIL = 'NODE_TYPE_EMAIL';
export const NODE_TYPE_SEGMENT_OPENED = 'NODE_TYPE_SEGMENT_OPENED';
export const NODE_TYPE_SEGMENT_CLOSED = 'NODE_TYPE_SEGMENT_CLOSED';
export const NODE_TYPE_TIMING = 'NODE_TYPE_TIMING';
